USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
# RATING_FIELD: rating
TIME_FIELD: timestamp

MAX_ITEM_LIST_LENGTH: 100

load_col:
    inter: [user_id, item_id, timestamp]

data_path: /dev/shm/data
dataset: BasketRecommendation

# training config
train_batch_size: 1024 
stopping_step: 10 
epochs: 500
learning_rate: 0.0001
train_neg_sample_args: {
    'distribution': 'uniform', 
    'sample_num': 4, 
    'dynamic': False}

# evaluation
eval_args:
    group_by: user
    order: TO
    split: {'LS': 'valid_and_test'}
    mode: full #pop100 
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 20
valid_metric: Recall@20

# model config: GRU4Rec
embedding_size: 64
hidden_size: 128
num_layers: 1
dropout_prob: 0.3
loss_type: 'BPR'

# model config: SASRec, BERT4Rec
hidden_size: 128
#inner_size
#n_layers
#n_heads
#hidden_dropout_prob
#attn_dropout_prob
#hidden_act
loss_type: 'BPR'

# refers from: https://recbole.io/docs/get_started/started/sequential.html
